/*You are given two dices. Each dice has 2 faces and can generate a number between 1 and 6.
The minimum number generated by the two dices is 2 and maximum number is 12. 
Throw the dices and if the number generated is less than or equal to 5 you lose and if it is 8 or greater then you win. 
Otherwise, it is a tie. */
using System;

class Program
{

static void Main()
{
    int randomNum;
    int playerWins = 0;

    Random random = new Random();

    Console.WriteLine($"Press any key to roll the dices.");
    Console.ReadKey(); //waits for player to press any key

    for (int i = 0; i < 3; i++)
    {
        randomNum = random.Next(2, 13); //generates roll
        Console.WriteLine($"\nYou rolled {randomNum}.");

        //if player rolls 8 or more
        if (randomNum >= 8)
        {
            playerWins++;
            Console.WriteLine($"You win this round!");
        }
        //if player rolls 5 or less
        else if (randomNum <= 5)
        {
            Console.WriteLine($"You lose this round.");
        }
        //if player rolls 6 or 7
        else
        {
            Console.WriteLine($"You tied this round.");
        }

    }
        //displays score
        Console.WriteLine($"\nYou won {playerWins} round(s).");
    }
}
